import test from 'node:test';
import assert from 'node:assert/strict';
import { initialData, cents, total, blankQuote, sendQuote, decideQuote, reviseQuote, newJob, advanceJob, activeJob, advanceOrder, cancelOrder, reserved, receivePayment, paid, balance, cashExpected, tableOrders, closeTable } from '../lib/operations/model.ts';
import { resolveCustomer } from '../lib/operations/customers.ts';
import { newKronosVisit, upsertKronosVisit, updateKronosVisit, setKronosDealMeta, kronosSignal } from '../lib/operations/kronos.ts';
// Test fixtures exist only in this file; no demonstration records enter the app.
const line=()=>({id:'line-test',kind:'Serviço',description:'Serviço de teste',brand:'',quantity:1,price:10000});
function workspace(){const d=initialData();d.customers.push({id:'c',name:'Cliente de teste',phone:'',email:'',notes:''});d.assets.push({id:'a',customerId:'c',identifier:'TESTE',model:'Ativo de teste',year:'',meter:''});return d;}
const jobInput={customerId:'c',assetId:'a',type:'Reparo',technician:'',due:'',complaint:'Relato de teste',diagnosis:'',notes:''};
function order(d,id='order',quantity=1){const o={id,number:d.orders.length+1,customerId:'c',customerName:'Teste',phone:'',address:'',channel:'Balcão',tableId:'',lines:[{...line(),id:`line-${id}`,kind:'Produto',productId:'p',quantity}],notes:'',status:'Novo',delivery:'',fee:0,discount:0,createdAt:'2026-09-08T12:00:00.000Z',events:[],stockConsumed:false,reserved:false};d.orders.push(o);return o;}
function product(d,stock=5){d.products.push({id:'p',name:'Produto de teste',price:10000,category:'Teste',description:'',available:true,stockControlled:true,stock,minimum:1,allergens:'',preparation:0});}
function shift(d,id='shift'){const s={id,openedAt:'2026-09-08T12:00:00Z',closedAt:'',initial:2000,counted:0,note:'',operator:'Teste'};d.shifts.push(s);return s;}
test('money preserves cents and rejects invalid amounts/discounts',()=>{assert.equal(cents('12,34'),1234);assert.equal(total([{...line(),quantity:1.5,price:333}],0),500);assert.throws(()=>cents('-1'));assert.throws(()=>total([line()],10001));assert.throws(()=>total([{...line(),quantity:0}]));});
test('each app starts empty with its own data and light theme',()=>{const a=initialData(),b=initialData();a.customers.push({id:'x'});assert.equal(b.customers.length,0);assert.equal(b.settings.theme,'light');assert.equal(b.orders.length,0);assert.equal(b.responses.length,0);});
test('progressive customer resolver reuses strong identity and does not silently merge homonyms',()=>{const d=initialData();d.customers.push({id:'a',name:'Carlos Silva',phone:'11911111111',email:'',notes:''},{id:'b',name:'Carlos Silva',phone:'11922222222',email:'carlos2@teste.com',notes:''});assert.equal(resolveCustomer(d,'Carlos Silva',{phone:'11922222222'}).id,'b');assert.equal(resolveCustomer(d,'Outro nome',{email:'carlos2@teste.com'}).id,'b');assert.throws(()=>resolveCustomer(d,'Carlos Silva'));const created=resolveCustomer(d,'Cliente novo',{phone:'11933333333'});assert.equal(created.name,'Cliente novo');assert.equal(d.customers.length,3);});
test('opening an appointment twice produces the same OS and keeps numbering unique',()=>{const d=workspace();d.appointments.push({id:'appointment',customerId:'c',assetId:'a',status:'Agendado'});const id=newJob(d,jobInput,'appointment');assert.equal(newJob(d,jobInput,'appointment'),id);newJob(d,jobInput);assert.deepEqual(d.jobs.map(j=>j.number),[1,2]);});
test('OS rejects unrelated client and asset',()=>{const d=workspace();d.customers.push({id:'other'});assert.throws(()=>newJob(d,{...jobInput,customerId:'other'}));assert.equal(d.jobs.length,0);});
test('diagnosis and approval gate execution, and double clicks do not skip stages',()=>{const d=workspace();const id=newJob(d,jobInput);const j=d.jobs[0];advanceJob(d,id,'Identificação');advanceJob(d,id,'Identificação');assert.equal(j.stage,'Diagnóstico');assert.throws(()=>advanceJob(d,id));j.diagnosis='Análise registrada';advanceJob(d,id);assert.equal(j.stage,'Orçamento');assert.throws(()=>advanceJob(d,id));j.quote.status='Aprovado';j.quote.lines=[line()];advanceJob(d,id);assert.equal(j.tasks.length,1);assert.throws(()=>advanceJob(d,id));j.tasks[0].done=true;advanceJob(d,id);advanceJob(d,id);assert.equal(j.status,'Pronto para retirada');advanceJob(d,id);assert.equal(activeJob(j),false);});
test('disabled optional modules still require a real execution before conference',()=>{const d=workspace();d.settings.budgetEnabled=false;d.settings.diagnosisEnabled=false;const id=newJob(d,jobInput);const j=d.jobs[0];advanceJob(d,id);assert.equal(j.stage,'Execução');assert.throws(()=>advanceJob(d,id),/ao menos uma tarefa real/);j.tasks.push({id:'task',description:'Executar reparo',done:false});assert.throws(()=>advanceJob(d,id),/Conclua os serviços/);j.tasks[0].done=true;advanceJob(d,id);assert.equal(j.stage,'Conferência');});
test('quote decisions require valid version and cannot conflict',()=>{const q=blankQuote(1);q.lines=[line()];q.validUntil='2099-01-01';sendQuote(q);assert.throws(()=>decideQuote(q,true,''));decideQuote(q,true,'Confirmado pelo cliente');assert.throws(()=>decideQuote(q,false,'Outra decisão'));assert.equal(q.status,'Aprovado');});
test('quote revision preserves exact prior content and removes stale approval',()=>{const q=blankQuote(1);q.lines=[line()];q.validUntil='2099-01-01';sendQuote(q);decideQuote(q,true,'Confirmação');reviseQuote(q);q.lines[0].price=123;assert.equal(q.versions[0].lines[0].price,10000);assert.equal(q.versions[0].status,'Aprovado');assert.equal(q.status,'Rascunho');assert.equal(q.version,2);assert.equal(q.decisionAt,undefined);});
test('Kronos planned visit becomes next action and quote progress aligns the opportunity stage',()=>{const d=initialData();d.settings.salesStages=['Identificado','Contato iniciado','Interesse confirmado','Proposta','Negociação'];d.customers.push({id:'c',name:'Cliente',phone:'',email:'',notes:''});d.deals.push({id:'deal',number:1,title:'Projeto',customerId:'c',value:50000,stage:'Identificado',source:'',nextAction:'',due:'',notes:'',lostReason:'',events:[],createdAt:new Date().toISOString()});const visit=newKronosVisit({customerId:'c',dealId:'deal',kind:'Visita',at:'2099-01-02T10:00:00',offering:'Projeto',objective:'Apresentar solução',quoteStatus:'Sem cotação',quoteValue:0,notes:'',address:'',lat:null,lng:null});upsertKronosVisit(d,visit);const task=d.tasks.find(item=>item.id===`kronos-visit:${visit.id}`);assert.ok(task);assert.equal(task.done,false);assert.match(d.deals[0].nextAction,/Visita/);assert.notEqual(kronosSignal(d,d.deals[0],d.settings.salesStages).label,'Atenção');updateKronosVisit(d,visit.id,{status:'Realizada'});assert.equal(task.done,true);assert.equal(d.deals[0].nextAction,'');setKronosDealMeta(d,'deal',{quoteStatus:'Enviada'});assert.equal(d.deals[0].stage,'Proposta');});
test('acceptance reserves stock and prevents another order from overselling',()=>{const d=workspace();product(d,2);const a=order(d,'one',2);const b=order(d,'two',1);advanceOrder(d,a.id);assert.equal(reserved(d,'p'),2);assert.throws(()=>advanceOrder(d,b.id));assert.equal(d.products[0].stock,2);});
test('stock is consumed only once and partial kitchen items cannot finish',()=>{const d=workspace();product(d);const o=order(d);advanceOrder(d,o.id,'Novo');advanceOrder(d,o.id,'Novo');assert.equal(o.status,'Aceito');advanceOrder(d,o.id,'Aceito');advanceOrder(d,o.id,'Aceito');assert.equal(d.products[0].stock,4);assert.equal(d.stockMovements.length,1);assert.throws(()=>advanceOrder(d,o.id));o.lines[0].done=true;advanceOrder(d,o.id);assert.equal(o.status,'Pronto');});
test('cancel before cooking releases reservation, after cooking does not restore stock',()=>{const d=workspace();product(d);const a=order(d,'one');advanceOrder(d,a.id);cancelOrder(d,a.id,'Cancelamento de teste');assert.equal(reserved(d,'p'),0);assert.equal(d.products[0].stock,5);const b=order(d,'two');advanceOrder(d,b.id);advanceOrder(d,b.id);cancelOrder(d,b.id,'Cancelamento após preparo');assert.equal(d.products[0].stock,4);});
test('delivery must be handed over before operational completion',()=>{const d=workspace();const o=order(d);o.channel='Delivery';o.status='Pronto';o.delivery='Saiu para entrega';assert.throws(()=>advanceOrder(d,o.id));o.delivery='Entregue';advanceOrder(d,o.id);assert.equal(o.status,'Concluído');});
test('Artemis keeps operational completion visible until the financial thread is settled',()=>{const d=workspace();const o=order(d);o.status='Pronto';advanceOrder(d,o.id);assert.equal(o.status,'Concluído');assert.match(o.events.at(-1).text,/saldo pendente/);shift(d);receivePayment(d,o.id,10000,'Pix');assert.equal(balance(d,o),0);assert.match(o.events.at(-1).text,/Saldo quitado/);});
test('payments require open shift, preserve split cents and reject overpayment',()=>{const d=workspace();const o=order(d);assert.throws(()=>receivePayment(d,o.id,100,'Pix'));shift(d);receivePayment(d,o.id,3333,'Pix');receivePayment(d,o.id,3333,'Cartão de débito');receivePayment(d,o.id,3334,'Dinheiro');assert.equal(balance(d,o),0);assert.equal(paid(d,o.id),10000);assert.throws(()=>receivePayment(d,o.id,1,'Pix'));});
test('cash drawer includes only cash and refund belongs to the current shift',()=>{const d=workspace();const o=order(d);const s=shift(d);receivePayment(d,o.id,5000,'Pix');receivePayment(d,o.id,5000,'Dinheiro');assert.equal(cashExpected(d,s),7000);s.closedAt='2026-09-08T14:00:00Z';const later=shift(d,'later');d.payments.find(p=>p.method==='Dinheiro').refunded=5000;d.movements.push({id:'r',shiftId:later.id,kind:'Devolução',amount:5000,method:'Dinheiro'});assert.equal(cashExpected(d,s),7000);assert.equal(cashExpected(d,later),-3000);});
test('a transferred older order remains bound to the destination table session',()=>{const d=workspace();const o=order(d);const t={id:'table',name:'Mesa de teste',seats:2,openedAt:'2026-09-08T13:00:00.000Z',closedAt:''};d.tables.push(t);o.channel='Mesa';o.tableId=t.id;o.tableSession=t.openedAt;assert.equal(tableOrders(d,t).length,1);assert.throws(()=>closeTable(d,t.id));shift(d);receivePayment(d,o.id,10000,'Pix');o.status='Concluído';closeTable(d,t.id);assert.equal(t.openedAt,'');t.openedAt='2026-09-08T16:00:00.000Z';assert.equal(tableOrders(d,t).length,0);});
test('cancelled paid orders keep refund pending and prevent closing table',()=>{const d=workspace();const o=order(d);const t={id:'table',name:'Mesa',seats:2,openedAt:'2026-09-08T11:00:00.000Z',closedAt:''};d.tables.push(t);o.tableId=t.id;shift(d);receivePayment(d,o.id,10000,'Pix');cancelOrder(d,o.id,'Cliente desistiu');assert.equal(paid(d,o.id),10000);assert.throws(()=>closeTable(d,t.id));});
