import { corporateUi } from './corporate';
import { AppId } from './model';
export const navigation:Record<AppId,{name:string;subtitle:string;short:string;sections:{path:string;label:string;icon:string}[]}>={
 zeus:{name:'Zeus',subtitle:'Oficina',short:'Z',sections:[{path:'inicio',label:corporateUi.homeLabel,icon:'home'},{path:'dashboard',label:'Dashboard',icon:'chart'},{path:'agendamentos',label:'Agendamentos',icon:'calendar'},{path:'atendimentos',label:'Atendimentos',icon:'wrench'},{path:'orcamentos',label:'Orçamentos',icon:'file'},{path:'fiscal',label:'Nota fiscal',icon:'file'},{path:'clientes',label:'Clientes e veículos',icon:'users'},{path:'historico',label:'Histórico',icon:'history'}]},
 artemis:{name:'Artemis',subtitle:'Restaurante',short:'A',sections:[{path:'inicio',label:'Operação',icon:'home'},{path:'cardapio',label:'Cardápio',icon:'book'},{path:'caixa',label:'Caixa',icon:'wallet'},{path:'estoque',label:'Estoque',icon:'box'},{path:'fiscal',label:'Nota fiscal',icon:'file'},{path:'clientes',label:'Clientes',icon:'users'},{path:'relatorios',label:'Relatórios',icon:'chart'}]},
 'athena-pesquisa':{name:'Athena',subtitle:'Pesquisa de satisfação',short:'A',sections:[{path:'inicio',label:corporateUi.homeLabel,icon:'home'},{path:'pesquisas',label:'Pesquisas',icon:'message'},{path:'respostas',label:'Respostas',icon:'inbox'},{path:'resultados',label:'Resultados',icon:'chart'}]},
 kronos:{name:'Kronos',subtitle:'Vendas',short:'K',sections:[{path:'inicio',label:corporateUi.homeLabel,icon:'home'},{path:'cronograma',label:'Cronograma',icon:'calendar'},{path:'oportunidades',label:'Oportunidades',icon:'target'},{path:'atividades',label:'Acompanhamento',icon:'calendar'},{path:'clientes',label:'Carteira',icon:'users'},{path:'historico',label:'Histórico',icon:'history'}]},
 'athena-orcamentos':{name:'Athena',subtitle:'Orçamentos',short:'A',sections:[{path:'inicio',label:corporateUi.homeLabel,icon:'home'},{path:'orcamentos',label:'Orçamentos',icon:'file'},{path:'clientes',label:'Clientes',icon:'users'}]}
};
export function isApp(value:string):value is AppId{return Object.hasOwn(navigation,value)}
export const appPages=(app:AppId)=>[...navigation[app].sections.map(s=>s.path),'configuracoes',...(app==='artemis'?['pedidos','mesas','cozinha','cardapio-digital']:[])];
